server:
  port: 5235
spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.206.201:9068
    gateway:
      discovery:
        locator:
          enabled: true
  main:
    web-application-type: reactive